./adb shell pm disable-user com.miui.systemAdSolution
./adb shell pm disable-user com.miui.analytics
./adb shell pm disable-user com.xiaomi.gamecenter.sdk.service
./adb shell pm disable-user com.sohu.inputmethod.sogou.xiaomi
./adb shell pm disable-user com.miui.player
./adb shell pm disable-user com.miui.video
./adb shell pm disable-user com.miui.translation.kingsoft
./adb shell pm disable-user com.android.email
./adb shell pm disable-user com.miui.hybrid
./adb shell pm disable-user com.miui.bugreport
./adb shell pm disable-user com.milink.service
./adb shell pm disable-user com.android.browser
./adb shell pm disable-user com.miui.yellowpage
./adb shell pm disable-user com.xiaomi.payment
./adb shell pm disable-user com.miui.voiceassist
./adb shell pm disable-user com.miui.touchassistant
./adb shell pm disable-user com.miui.miservice
./adb shell pm disable-user com.xiaomi.ab
./adb shell pm disable-user com.xiaomi.aiasst.service
::./adb shell pm disable-user com.xiaomi.joyose
./adb shell pm disable-user com.xiaomi.mi_connect_service
./adb shell pm disable-user com.miui.nextpay
./adb shell pm disable-user com.miui.personalassistant
exit